# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=64)),
                ('program_executed_datetime', models.DateTimeField()),
                ('customer_name', models.CharField(max_length=64)),
            ],
        ),
    ]
